<?php
return [
    [
        "href"=>"/characters",
        "text"=>"CHARACTERS"
    ],
    [
        "href"=>"/comics",
        "text"=>"COMICS"
    ],
    [
        "href"=>"/cmovies",
        "text"=>"MOVIES"
    ],
    [
        "href"=>"/games",
        "text"=>"GAMES"
    ],
    [
        "href"=>"/tv",
        "text"=>"TV"
    ],
    [
        "href"=>"/collectibles",
        "text"=>"COLLECTIBLES"
    ],
];